### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by chris985** [bloodypenguin/Skylines-SurfacePainter#3]
Hi there, I see this hasn't been updated in a while but in case anyone sees this and the debug info is helpful in any way I thought I'd post this here. This great mod is not working any longer.

`A Mod caused an error [ModException]

Details:
System.IndexOutOfRangeException: Array index is out of range.
  at OptionsMainPanel.AddUserMods () [0x00000] in <filename unknown>:0 `

This happens as soon as the game launches and upon loading a map with the mod enabled. Then, the mod does not appear or work either.

**Comment by bloodypenguin** [comment]
I see this and the mod works. I tested it just today ;)
